### ISSUE TITLE
Duplicate history entries when writing to Redis

### ISSUE THREAD

**Issue by siku2** [gieseladev/giesela#58]
For some reason when dumping the current player state to redis it can happen that the current entry already shows up in the history even though said entry hasn't actually finished playing yet. When loading the state from redis there will already be a history entry of the entry that is currently playing, leading to a duplicate once the entry finishes playing.

I gotta be honest, I have absolutely no idea yet why this occurs and I'm currently investigating.

When an entry finishes playing and is "pushed" to the history deque there should be a log saying "finished playing x". I haven't been able to find such a log when Giesela is shutting down so it shouldn't be possible that the entry was added to the history...

**Comment by shikhir-arora** [comment]
Perhaps the shutdown triggers the LL `TrackEndEvent` which gets picked up on shutdown, though the log stuff is odd. Will look out for this.

**Comment by siku2** [comment]
Since Giesela is bootstrapped it should've been possible to catch a call to the [`Queue.push_history`](https://github.com/gieseladev/giesela/blob/refresh/giesela/queue.py#L103) method. Curiously this method was never called during shutdown (or restart).

I will try to investigate whether it occurs during the dump or load operation.
