### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by PenetratingShot** [GieselaDev/Giesela#60]
It would be nice if I actually knew how to make edits to this project. I'm not really accustomed to the file structure so it would be great if you guys could create a file called `CONTRIBUTING.md` in `/` to help people like me :)

**Comment by shikhir-arora** [comment]
Hey -- sorry for the delay in response, and thank you for your suggestion. Giesela is and always will be an open-source application, but we don't have a contribution guideline yet. Giesela is a music suite that consists of a lot of moving parts (API's, middleware and microservices) and there's a lot of behind-the-scenes work as we haven't launched the bot yet. Most of it is public, some of it is private only until we launch, where it will be made open-source (just the frontend right now, really). These are published on the [GieselaDev organization](https://github.com/GieselaDev) -- also, a rough goal/countdown can be seen on our landing page (which is also [open-source](https://github.com/GieselaDev/landing)): https://giesela.io

The master branch of this project does contain instructions on how to run the bot simply for the sake that you can do so, however, it is currently nothing like the bot will be when it launches. It works fine though for individual server use, which is another reason why we put instructions on installing it and uploaded it to the Docker hub, etc. The only reason I updated it, for example, a few days ago was that we still run it to test some of our frontend stuff, and I had to update dependencies (like `youtube-dl` and `ffmpeg` which we aren't using in the actual final bot, but in the current master branch that is still used to process and download audio). I like to keep things (such as production code) as in-sync with Git, so I updated the Git repo as well, and for the fact that I update it from Dockerhub as well automatically. 🙃 

That being said, we're always happy to have interested contributors, though at this stage so much is not really reflected publicly or documented that it's a bit tough. However, I know you are in my server and have my Discord info, so just shoot me a DM with what your interest in contributing is, etc. and we'll be happy to discuss. Sorry to sound so formal, again, once the project launches (keep an eye on [the website](https://giesela.io)  

With that, going to close this issue for now, but you know how to reach me.
